import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

enum AppLanguage {
  english('en', 'English', '🇬🇧'),
  hindi('hi', 'हिन्दी', '🇮🇳'),
  malayalam('ml', 'മലയാളം', '🇮🇳'),
  tamil('ta', 'தமிழ்', '🇮🇳'),
  kannada('kn', 'ಕನ್ನಡ', '🇮🇳'),
  telugu('te', 'తెలుగు', '🇮🇳'),
  marathi('mr', 'मराठी', '🇮🇳'),
  bengali('bn', 'বাংলা', '🇮🇳'),
  gujarati('gu', 'ગુજરાતી', '🇮🇳');
  final String code;
  final String nativeName;
  final String flag;
  const AppLanguage(this.code, this.nativeName, this.flag);
}

class LanguageService extends ChangeNotifier {
  static const String _languageKey = 'selected_language';
  static const String _onboardingKey = 'onboarding_completed';
  AppLanguage _currentLanguage = AppLanguage.english;
  bool _onboardingCompleted = false;
  AppLanguage get currentLanguage => _currentLanguage;
  bool get onboardingCompleted => _onboardingCompleted;

  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    final savedCode = prefs.getString(_languageKey);
    _onboardingCompleted = prefs.getBool(_onboardingKey) ?? false;
    if (savedCode != null) {
      _currentLanguage = AppLanguage.values.firstWhere(
        (lang) => lang.code == savedCode, orElse: () => AppLanguage.english);
    }
  }

  Future<void> setLanguage(AppLanguage language) async {
    _currentLanguage = language;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, language.code);
    notifyListeners();
  }

  Future<void> completeOnboarding() async {
    _onboardingCompleted = true;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_onboardingKey, true);
    notifyListeners();
  }

  String t(String key) => _translations[_currentLanguage.code]?[key] ?? _translations['en']?[key] ?? key;

  static final Map<String, Map<String, String>> _translations = {
    'en': _en, 'hi': _hi, 'ml': _ml, 'ta': _ta, 'kn': _kn,
    'te': _te, 'mr': _mr, 'bn': _bn, 'gu': _gu,
  };

  static const _en = {
    // Onboarding
    'onboarding_title_1': 'Welcome to Emptyko',
    'onboarding_desc_1': 'Smart waste management at your fingertips. Schedule pickups, track bins, and earn eco-points!',
    'onboarding_title_2': 'Smart Bin Monitoring',
    'onboarding_desc_2': 'Real-time IoT sensors track your bin levels. Get alerts when bins are full and auto-schedule pickups.',
    'onboarding_title_3': 'Sell & Recycle',
    'onboarding_desc_3': 'Turn your recyclable waste into cash! List items on our marketplace and contribute to a greener planet.',
    'choose_language': 'Choose Your Language',
    'choose_language_desc': 'Select your preferred language to get started',
    'get_started': 'Get Started',
    'next': 'Next',
    'skip': 'Skip',
    'back': 'Back',
    // Login
    'welcome_back': 'Welcome Back!',
    'enter_phone': 'Enter your phone number to get started',
    'verify_otp': 'Verify OTP',
    'enter_otp': 'Enter the 6-digit code sent to your phone',
    'almost_done': 'Almost Done!',
    'setup_email': 'Set up your email & password to complete login',
    'phone': 'Phone',
    'verify': 'Verify',
    'account': 'Account',
    'continue_google': 'Continue with Google',
    'or_continue_phone': 'or continue with phone',
    'or_login_email': 'or login with email',
    'sign_in_to_continue': 'Sign in to continue your eco-friendly journey',
    'enter_phone_number': 'Enter phone number',
    'send_otp': 'Send OTP',
    'phone_secure_note': 'Your phone number is secure and will only be used for verification.',
    'remember_me': 'Remember me',
    'forgot_password': 'Forgot Password?',
    'login': 'Login',
    'complete_sign_in': 'Complete Sign In',
    'dont_have_account': "Don't have an account? ",
    'sign_up': 'Sign Up',
    'resend_otp': 'Resend OTP',
    'verify_otp_btn': 'Verify OTP',
    'change_number': 'Change Number',
    'enter_otp_label': 'Enter OTP',
    'sent_to': 'Sent to',
    'didnt_receive': "Didn't receive the code?",
    'resend_in': 'Resend in',
    'phone_verified': 'Phone Verified',
    'email_address': 'Email Address',
    'password': 'Password',
    'enter_email': 'Please enter your email',
    'valid_email': 'Please enter a valid email',
    'enter_password': 'Please enter your password',
    'google_coming_soon': 'Google Sign-In coming soon! Use phone + email login.',
    'otp_sent_to': 'OTP sent to',
    'phone_verified_msg': 'Phone verified! Now set up your email & password.',
    'complete_otp': 'Please enter complete OTP',
    'valid_phone': 'Please enter a valid phone number',
    // Signup
    'create_account': 'Create Account',
    'join_eco': 'Join us and start your eco-friendly journey',
    'or_signup_email': 'or sign up with email',
    'full_name': 'Full Name',
    'phone_number': 'Phone Number',
    'confirm_password': 'Confirm Password',
    'enter_name': 'Please enter your name',
    'enter_phone_num': 'Please enter phone number',
    'valid_number': 'Enter valid number',
    'enter_a_password': 'Please enter a password',
    'password_min': 'Password must be at least 8 characters',
    'confirm_pass': 'Please confirm your password',
    'passwords_no_match': 'Passwords do not match',
    'agree_terms': 'Please agree to Terms & Conditions',
    'i_agree': 'I agree to the ',
    'terms_service': 'Terms of Service',
    'and': ' and ',
    'privacy_policy': 'Privacy Policy',
    'already_account': 'Already have an account? ',
    'sign_in': 'Sign In',
    'account_created': 'Account created! Now verify your phone.',
    'google_signup_soon': 'Google Sign-In coming soon! Use email signup.',
    // Home
    'home': 'Home',
    'pickup': 'Pickup',
    'smart_bin': 'Smart Bin',
    'history': 'History',
    'market': 'Market',
    'welcome_back_name': 'Welcome Back,',
    'keep_city_clean': "Let's keep our\ncity clean today!",
    'eco_points_earned': 'Eco Points earned',
    'quick_actions': 'Quick Actions',
    'schedule_pickup': 'Schedule\nPickup',
    'smart_bin_action': 'Smart\nBin',
    'sell_recyclables': 'Sell\nRecyclables',
    'plans_subs': 'Plans &\nSubs',
    'smart_bin_status': 'Smart Bin Status',
    'view_all': 'View All →',
    'upcoming_pickup': 'Upcoming Pickup',
    'scheduled_pickup': 'Scheduled Pickup',
    'tomorrow': 'Tomorrow, 9-11 AM',
    'confirmed': 'Confirmed',
    'details': 'Details',
    'track': 'Track',
    'eco_impact': 'Your Eco Impact 🌿',
    'waste_recycled': 'Waste\nRecycled',
    'pickups_completed': 'Pickups\nCompleted',
    'eco_points': 'Eco\nPoints',
    'upgrade_eco_pro': 'Upgrade to EcoPro!',
    'unlimited_pickups': 'Unlimited pickups, priority scheduling & more',
    'kitchen_waste': 'Kitchen Waste',
    'auto_pickup_scheduled': 'Auto-pickup scheduled',
    'recyclables': 'Recyclables',
    'normal': 'Normal',
    'location_label': 'Your Location',
    // Schedule Pickup
    'schedule_pickup_title': 'Schedule Pickup',
    'pickup_location': 'Pickup Location',
    'building_name': 'Building / House Name',
    'street_address': 'Street Address',
    'landmark': 'Landmark (Optional)',
    'select_date': 'Select Date',
    'select_time': 'Select Time',
    'schedule_summary': 'Schedule Summary',
    'date': 'Date',
    'time': 'Time',
    'location': 'Location',
    'confirm_schedule': 'Confirm Schedule',
    'change_address': 'Change Address',
    'saved_address': 'Saved Address',
    'current_location': 'Current Location',
    'enter_building': 'Enter building/house name',
    'enter_street': 'Enter street address',
    'enter_landmark': 'Enter nearby landmark',
    // Smart Bin
    'smart_bin_title': 'Smart Bin',
    'bin_overview': 'Bin Overview',
    'total_bins': 'Total\nBins',
    'alerts': 'Alerts',
    'connected': 'Connected',
    'auto_schedule': 'Auto-Schedule',
    'auto_schedule_desc': 'Bins above 80% fill level will automatically schedule a pickup.',
    'weekly_stats': 'Weekly Stats',
    'fill_level': 'Fill Level',
    'last_emptied': 'Last Emptied',
    'alert_btn': 'Alert',
    'schedule_btn': 'Schedule',
    'history_btn': 'History',
    // History
    'history_title': 'History',
    'all_activity': 'All Activity',
    'this_month': 'This Month',
    'pickups_tab': 'Pickups',
    'recycling_tab': 'Recycling',
    'transactions_tab': 'Transactions',
    'all': 'All',
    'completed': 'Completed',
    'pending': 'Pending',
    'cancelled': 'Cancelled',
    'view_details': 'View Details',
    'total_earned': 'Total Earned',
    'total_spent': 'Total Spent',
    'net_savings': 'Net Savings',
    // Marketplace
    'marketplace': 'Marketplace',
    'sell_waste': 'Sell Waste',
    'search_items': 'Search recyclable items...',
    'total_earnings': 'Total Earnings',
    'items_sold': 'Items Sold',
    'active_listings': 'Active Listings',
    'pending_pickup_label': 'Pending Pickup',
    'market_rates': 'Market Rates',
    'your_listings': 'Your Listings',
    'sell_new_item': 'Sell New Item',
    'item_name': 'Item Name',
    'weight_kg': 'Weight (kg)',
    'description': 'Description',
    'list_item': 'List Item',
    'cancel': 'Cancel',
    'category': 'Category',
    'papers': 'Papers',
    'plastics': 'Plastics',
    'metals': 'Metals',
    'e_waste': 'E-Waste',
    'glass': 'Glass',
    'others': 'Others',
    // Pickup Details
    'pickup_details': 'Pickup Details',
    'waste_weight': 'Waste Weight',
    'estimated_weight': 'Estimated Weight',
    'quick_select': 'Quick Select',
    'waste_type': 'Waste Type',
    'additional_options': 'Additional Options',
    'fragile_items': 'Fragile Items',
    'heavy_items': 'Heavy Items (>20kg)',
    'special_handling': 'Special Handling',
    'notes': 'Notes for Driver',
    'add_notes': 'Add any special instructions...',
    'price_breakdown': 'Price Breakdown',
    'base_price': 'Base Price',
    'weight_charge': 'Weight Charge',
    'special_handling_fee': 'Special Handling',
    'discount': 'Discount',
    'total': 'Total',
    'proceed_payment': 'Proceed to Payment',
    'mixed': 'Mixed',
    'organic': 'Organic',
    'plastic': 'Plastic',
    'metal': 'Metal',
    'paper': 'Paper',
    'hazardous': 'Hazardous',
    // Pickup Tracking
    'track_pickup': 'Track Pickup',
    'live': 'LIVE',
    'arriving_in': 'Arriving in',
    'mins': 'mins',
    'driver_on_way': 'Driver is on the way',
    'pickup_confirmed_label': 'Pickup Confirmed',
    'driver_assigned': 'Driver Assigned',
    'on_the_way': 'On the Way',
    'arrived': 'Arrived',
    'driver_info': 'Driver Info',
    'call': 'Call',
    'message': 'Message',
    'rating': 'Rating',
    'trips': 'Trips',
    'pickup_info': 'Pickup Info',
    'waste_type_label': 'Waste Type',
    'weight': 'Weight',
    'amount': 'Amount',
    // Payment
    'payment': 'Payment',
    'amount_to_pay': 'Amount to Pay',
    'order_summary': 'Order Summary',
    'pickup_charge': 'Pickup Charge',
    'service_fee': 'Service Fee',
    'taxes': 'Taxes',
    'payment_method': 'Payment Method',
    'upi': 'UPI',
    'card': 'Card',
    'net_banking': 'Net Banking',
    'cash': 'Cash',
    'wallet': 'Wallet',
    'promo_code': 'Promo Code',
    'apply': 'Apply',
    'enter_promo': 'Enter promo code',
    'pay_now': 'Pay Now',
    'payment_success': 'Payment Successful!',
    'track_your_pickup': 'Track Your Pickup',
    'back_to_home': 'Back to Home',
    'transaction_id': 'Transaction ID',
    'payment_mode': 'Payment Mode',
    // Email Verification
    'verify_email_title': 'Email Not Verified',
    'verify_email_desc': 'Please verify your email address to continue. Check your inbox for the verification link.',
    'verify_your_email': 'Verify Your Email',
    'verification_sent_to': 'A verification email has been sent to',
    'check_inbox_verify': 'Check your inbox and click the verification link, then tap the button below.',
    'verification_email_sent': 'Verification email sent! Check your inbox.',
    'resend_verification': 'Resend Verification Email',
    'already_verified': "I've Already Verified",
    'i_have_verified': "I've Verified My Email",
    'email_not_verified_yet': 'Email not verified yet. Please check your inbox.',
    'back_to_login': 'Back to Login',
    // Forgot Password
    'forgot_password_desc': 'Enter your email address and we will send you a link to reset your password.',
    'send_reset_link': 'Send Reset Link',
    'reset_email_sent': 'Password reset email sent! Check your inbox.',
    'verification_success': 'Verification Successful!',
    'continue_text': 'Continue',
    // Subscription
    'subscription': 'Subscription',
    'choose_plan': 'Choose Your Plan',
    'choose_plan_desc': 'Upgrade for unlimited pickups and premium features',
    'current_plan': 'Current Plan',
    'free_plan': 'Free',
    'basic_plan': 'Basic',
    'pro_plan': 'Pro',
    'enterprise_plan': 'Enterprise',
    'per_month': '/month',
    'popular': 'Popular',
    'subscribe_now': 'Subscribe Now',
    'features': 'Features',
    'benefits': 'Benefits',
    'faq': 'FAQ',
    'priority_pickup': 'Priority Pickup',
    'smart_analytics': 'Smart Analytics',
    'eco_rewards': 'Eco Rewards',
    'unlimited': 'Unlimited',
    // Settings
    'settings': 'Settings',
    'language': 'Language',
    'notifications': 'Notifications',
    'profile': 'Profile',
    'logout': 'Logout',
    'logout_confirm': 'Are you sure you want to log out?',
    'profile_updated': 'Profile updated successfully!',
  };

  static const _hi = {
    'onboarding_title_1': 'Emptyko में आपका स्वागत है',
    'onboarding_desc_1': 'आपकी उंगलियों पर स्मार्ट कचरा प्रबंधन। पिकअप शेड्यूल करें, बिन ट्रैक करें!',
    'onboarding_title_2': 'स्मार्ट बिन मॉनिटरिंग',
    'onboarding_desc_2': 'रियल-टाइम IoT सेंसर आपके बिन लेवल ट्रैक करते हैं।',
    'onboarding_title_3': 'बेचें और रीसायकल करें',
    'onboarding_desc_3': 'अपने रीसायकल योग्य कचरे को पैसे में बदलें!',
    'choose_language': 'अपनी भाषा चुनें',
    'choose_language_desc': 'शुरू करने के लिए अपनी पसंदीदा भाषा चुनें',
    'get_started': 'शुरू करें', 'next': 'अगला', 'skip': 'छोड़ें', 'back': 'पीछे',
    'welcome_back': 'वापसी पर स्वागत है!',
    'enter_phone': 'शुरू करने के लिए फ़ोन नंबर दर्ज करें',
    'verify_otp': 'OTP सत्यापित करें',
    'enter_otp': '6-अंकीय कोड दर्ज करें',
    'almost_done': 'लगभग हो गया!',
    'setup_email': 'ईमेल और पासवर्ड सेट करें',
    'phone': 'फ़ोन', 'verify': 'सत्यापित', 'account': 'अकाउंट',
    'continue_google': 'Google से जारी रखें',
    'or_continue_phone': 'या फ़ोन से जारी रखें',
    'or_login_email': 'या ईमेल से लॉगिन करें',
    'sign_in_to_continue': 'अपनी इको-फ्रेंडली यात्रा जारी रखने के लिए साइन इन करें',
    'enter_phone_number': 'फ़ोन नंबर दर्ज करें',
    'send_otp': 'OTP भेजें',
    'phone_secure_note': 'आपका फ़ोन नंबर सुरक्षित है।',
    'remember_me': 'मुझे याद रखें',
    'forgot_password': 'पासवर्ड भूल गए?',
    'login': 'लॉगिन', 'complete_sign_in': 'साइन इन पूरा करें',
    'dont_have_account': 'अकाउंट नहीं है? ', 'sign_up': 'साइन अप करें',
    'resend_otp': 'OTP पुनः भेजें', 'verify_otp_btn': 'OTP सत्यापित करें',
    'enter_otp_label': 'OTP दर्ज करें', 'sent_to': 'भेजा गया',
    'didnt_receive': 'कोड नहीं मिला?', 'resend_in': 'पुनः भेजें',
    'phone_verified': 'फ़ोन सत्यापित', 'email_address': 'ईमेल पता',
    'password': 'पासवर्ड', 'enter_email': 'ईमेल दर्ज करें',
    'valid_email': 'मान्य ईमेल दर्ज करें', 'enter_password': 'पासवर्ड दर्ज करें',
    'create_account': 'अकाउंट बनाएं',
    'join_eco': 'हमसे जुड़ें और इको-फ्रेंडली यात्रा शुरू करें',
    'or_signup_email': 'या ईमेल से साइन अप करें',
    'full_name': 'पूरा नाम', 'phone_number': 'फ़ोन नंबर',
    'confirm_password': 'पासवर्ड पुष्टि', 'enter_name': 'नाम दर्ज करें',
    'enter_phone_num': 'फ़ोन नंबर दर्ज करें', 'valid_number': 'मान्य नंबर दर्ज करें',
    'enter_a_password': 'पासवर्ड दर्ज करें',
    'password_min': 'पासवर्ड कम से कम 8 अक्षर का होना चाहिए',
    'confirm_pass': 'पासवर्ड की पुष्टि करें',
    'passwords_no_match': 'पासवर्ड मेल नहीं खाते',
    'agree_terms': 'नियम और शर्तों से सहमत हों',
    'i_agree': 'मैं सहमत हूं ', 'terms_service': 'सेवा की शर्तें',
    'and': ' और ', 'privacy_policy': 'गोपनीयता नीति',
    'already_account': 'पहले से अकाउंट है? ', 'sign_in': 'साइन इन',
    'home': 'होम', 'pickup': 'पिकअप', 'smart_bin': 'स्मार्ट बिन',
    'history': 'इतिहास', 'market': 'मार्केट',
    'welcome_back_name': 'वापसी पर स्वागत,',
    'keep_city_clean': 'आज शहर को\nस्वच्छ रखें!',
    'eco_points_earned': 'इको पॉइंट्स अर्जित',
    'quick_actions': 'त्वरित कार्य',
    'schedule_pickup': 'पिकअप\nशेड्यूल',
    'smart_bin_action': 'स्मार्ट\nबिन',
    'sell_recyclables': 'रीसायकल\nबेचें',
    'plans_subs': 'प्लान और\nसब्स',
    'smart_bin_status': 'स्मार्ट बिन स्थिति',
    'view_all': 'सभी देखें →',
    'upcoming_pickup': 'आगामी पिकअप',
    'scheduled_pickup': 'शेड्यूल्ड पिकअप',
    'tomorrow': 'कल, 9-11 AM',
    'confirmed': 'पुष्टि', 'details': 'विवरण', 'track': 'ट्रैक',
    'eco_impact': 'आपका इको प्रभाव 🌿',
    'waste_recycled': 'कचरा\nरीसायकल', 'pickups_completed': 'पिकअप\nपूर्ण',
    'eco_points': 'इको\nपॉइंट्स',
    'upgrade_eco_pro': 'EcoPro में अपग्रेड करें!',
    'unlimited_pickups': 'असीमित पिकअप, प्राथमिक शेड्यूलिंग',
    'kitchen_waste': 'रसोई कचरा', 'recyclables': 'पुनर्चक्रण योग्य',
    'auto_pickup_scheduled': 'ऑटो-पिकअप शेड्यूल', 'normal': 'सामान्य',
    'schedule_pickup_title': 'पिकअप शेड्यूल',
    'pickup_location': 'पिकअप स्थान',
    'building_name': 'भवन / मकान का नाम',
    'street_address': 'गली का पता', 'landmark': 'लैंडमार्क (वैकल्पिक)',
    'select_date': 'तारीख चुनें', 'select_time': 'समय चुनें',
    'schedule_summary': 'शेड्यूल सारांश',
    'date': 'तारीख', 'time': 'समय', 'location': 'स्थान',
    'confirm_schedule': 'शेड्यूल पुष्टि करें',
    'smart_bin_title': 'स्मार्ट बिन', 'bin_overview': 'बिन अवलोकन',
    'total_bins': 'कुल\nबिन', 'alerts': 'अलर्ट', 'connected': 'कनेक्टेड',
    'auto_schedule': 'ऑटो-शेड्यूल',
    'auto_schedule_desc': '80% से ऊपर बिन स्वचालित पिकअप शेड्यूल करेंगे।',
    'weekly_stats': 'साप्ताहिक आँकड़े',
    'fill_level': 'भरा स्तर', 'last_emptied': 'अंतिम खाली',
    'history_title': 'इतिहास', 'all_activity': 'सभी गतिविधि',
    'this_month': 'इस महीने',
    'pickups_tab': 'पिकअप', 'recycling_tab': 'रीसायक्लिंग',
    'transactions_tab': 'लेनदेन',
    'all': 'सभी', 'completed': 'पूर्ण', 'pending': 'लंबित', 'cancelled': 'रद्द',
    'marketplace': 'मार्केटप्लेस', 'sell_waste': 'कचरा बेचें',
    'search_items': 'रीसायकल योग्य आइटम खोजें...',
    'total_earnings': 'कुल कमाई', 'items_sold': 'बेचे गए आइटम',
    'active_listings': 'सक्रिय लिस्टिंग',
    'market_rates': 'बाज़ार दरें', 'your_listings': 'आपकी लिस्टिंग',
    'sell_new_item': 'नया आइटम बेचें',
    'item_name': 'आइटम का नाम', 'weight_kg': 'वज़न (kg)',
    'description': 'विवरण', 'list_item': 'आइटम लिस्ट करें', 'cancel': 'रद्द करें',
    'pickup_details': 'पिकअप विवरण', 'waste_weight': 'कचरे का वज़न',
    'estimated_weight': 'अनुमानित वज़न', 'quick_select': 'क्विक सिलेक्ट',
    'waste_type': 'कचरे का प्रकार',
    'additional_options': 'अतिरिक्त विकल्प',
    'fragile_items': 'नाज़ुक आइटम', 'heavy_items': 'भारी आइटम (>20kg)',
    'special_handling': 'विशेष हैंडलिंग',
    'notes': 'ड्राइवर के लिए नोट्स', 'add_notes': 'विशेष निर्देश जोड़ें...',
    'price_breakdown': 'मूल्य विवरण', 'base_price': 'बेस मूल्य',
    'weight_charge': 'वज़न शुल्क', 'discount': 'छूट', 'total': 'कुल',
    'proceed_payment': 'भुगतान करें',
    'track_pickup': 'पिकअप ट्रैक करें', 'live': 'लाइव',
    'arriving_in': 'आगमन', 'mins': 'मिनट',
    'driver_on_way': 'ड्राइवर रास्ते में है',
    'driver_assigned': 'ड्राइवर नियुक्त', 'on_the_way': 'रास्ते में',
    'arrived': 'पहुंच गया', 'driver_info': 'ड्राइवर जानकारी',
    'call': 'कॉल', 'message': 'संदेश', 'rating': 'रेटिंग', 'trips': 'यात्राएं',
    'payment': 'भुगतान', 'amount_to_pay': 'भुगतान राशि',
    'order_summary': 'ऑर्डर सारांश',
    'payment_method': 'भुगतान विधि', 'pay_now': 'अभी भुगतान करें',
    'payment_success': 'भुगतान सफल!',
    'back_to_home': 'होम पर वापस',
    'subscription': 'सब्सक्रिप्शन', 'choose_plan': 'अपना प्लान चुनें',
    'current_plan': 'वर्तमान प्लान', 'subscribe_now': 'अभी सब्सक्राइब करें',
    'settings': 'सेटिंग्स', 'language': 'भाषा',
    'notifications': 'सूचनाएं', 'profile': 'प्रोफ़ाइल', 'logout': 'लॉगआउट',
    'category': 'श्रेणी', 'papers': 'कागज़', 'plastics': 'प्लास्टिक',
    'metals': 'धातु', 'e_waste': 'ई-कचरा', 'glass': 'काँच', 'others': 'अन्य',
    'mixed': 'मिश्रित', 'organic': 'जैविक', 'plastic': 'प्लास्टिक',
    'metal': 'धातु', 'paper': 'कागज़', 'hazardous': 'खतरनाक',
    'verify_phone': 'फ़ोन सत्यापित करें',
    'continue_text': 'जारी रखें',
    'location_label': 'आपका स्थान',
  };

  static const _ml = {
    'onboarding_title_1': 'Emptyko-ലേക്ക് സ്വാഗതം',
    'onboarding_desc_1': 'നിങ്ങളുടെ വിരൽത്തുമ്പിൽ സ്മാർട്ട് മാലിന്യ സംസ്കരണം.',
    'onboarding_title_2': 'സ്മാർട്ട് ബിൻ മോണിറ്ററിംഗ്',
    'onboarding_desc_2': 'റിയൽ-ടൈം IoT സെൻസറുകൾ നിങ്ങളുടെ ബിൻ ലെവലുകൾ ട്രാക്ക് ചെയ്യുന്നു.',
    'onboarding_title_3': 'വിൽക്കുക & റീസൈക്കിൾ ചെയ്യുക',
    'onboarding_desc_3': 'നിങ്ങളുടെ റീസൈക്കിൾ മാലിന്യം പണമാക്കി മാറ്റുക!',
    'choose_language': 'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക',
    'choose_language_desc': 'ആരംഭിക്കാൻ ഭാഷ തിരഞ്ഞെടുക്കുക',
    'get_started': 'ആരംഭിക്കുക', 'next': 'അടുത്തത്', 'skip': 'ഒഴിവാക്കുക', 'back': 'പിന്നിലേക്ക്',
    'welcome_back': 'സ്വാഗതം!', 'enter_phone': 'ഫോൺ നമ്പർ നൽകുക',
    'verify_otp': 'OTP സ്ഥിരീകരിക്കുക', 'enter_otp': '6-അക്ക കോഡ് നൽകുക',
    'almost_done': 'ഏകദേശം പൂർത്തിയായി!',
    'setup_email': 'ഇമെയിലും പാസ്‌വേഡും സജ്ജമാക്കുക',
    'phone': 'ഫോൺ', 'verify': 'സ്ഥിരീകരിക്കുക', 'account': 'അക്കൗണ്ട്',
    'continue_google': 'Google ഉപയോഗിച്ച് തുടരുക',
    'or_continue_phone': 'അല്ലെങ്കിൽ ഫോൺ ഉപയോഗിച്ച് തുടരുക',
    'or_login_email': 'അല്ലെങ്കിൽ ഇമെയിൽ ഉപയോഗിച്ച് ലോഗിൻ ചെയ്യുക',
    'sign_in_to_continue': 'നിങ്ങളുടെ ഇക്കോ യാത്ര തുടരാൻ സൈൻ ഇൻ ചെയ്യുക',
    'enter_phone_number': 'ഫോൺ നമ്പർ നൽകുക',
    'send_otp': 'OTP അയയ്ക്കുക',
    'phone_secure_note': 'നിങ്ങളുടെ ഫോൺ നമ്പർ സുരക്ഷിതമാണ്.',
    'remember_me': 'എന്നെ ഓർക്കുക', 'forgot_password': 'പാസ്‌വേഡ് മറന്നോ?',
    'login': 'ലോഗിൻ', 'complete_sign_in': 'സൈൻ ഇൻ പൂർത്തിയാക്കുക',
    'dont_have_account': 'അക്കൗണ്ട് ഇല്ലേ? ', 'sign_up': 'സൈൻ അപ്പ്',
    'resend_otp': 'OTP വീണ്ടും അയയ്ക്കുക', 'verify_otp_btn': 'OTP സ്ഥിരീകരിക്കുക',
    'enter_otp_label': 'OTP നൽകുക', 'sent_to': 'അയച്ചത്',
    'didnt_receive': 'കോഡ് ലഭിച്ചില്ലേ?', 'resend_in': 'വീണ്ടും അയയ്ക്കുക',
    'phone_verified': 'ഫോൺ സ്ഥിരീകരിച്ചു', 'email_address': 'ഇമെയിൽ വിലാസം',
    'password': 'പാസ്‌വേഡ്', 'enter_email': 'ഇമെയിൽ നൽകുക',
    'enter_password': 'പാസ്‌വേഡ് നൽകുക',
    'create_account': 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    'join_eco': 'ഞങ്ങളോടൊപ്പം ചേരൂ',
    'or_signup_email': 'അല്ലെങ്കിൽ ഇമെയിൽ ഉപയോഗിച്ച് സൈൻ അപ്പ്',
    'full_name': 'പൂർണ്ണ നാമം', 'phone_number': 'ഫോൺ നമ്പർ',
    'confirm_password': 'പാസ്‌വേഡ് സ്ഥിരീകരിക്കുക',
    'already_account': 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ? ', 'sign_in': 'സൈൻ ഇൻ',
    'home': 'ഹോം', 'pickup': 'പിക്കപ്പ്', 'smart_bin': 'സ്മാർട്ട് ബിൻ',
    'history': 'ചരിത്രം', 'market': 'മാർക്കറ്റ്',
    'welcome_back_name': 'തിരികെ സ്വാഗതം,',
    'keep_city_clean': 'ഇന്ന് നമ്മുടെ നഗരം\nവൃത്തിയാക്കാം!',
    'eco_points_earned': 'ഇക്കോ പോയിന്‍റ്‌സ് നേടി',
    'quick_actions': 'ദ്രുത പ്രവർത്തനങ്ങൾ',
    'schedule_pickup': 'പിക്കപ്പ്\nഷെഡ്യൂൾ',
    'smart_bin_action': 'സ്മാർട്ട്\nബിൻ', 'sell_recyclables': 'റീസൈക്കിൾ\nവിൽക്കുക',
    'plans_subs': 'പ്ലാനുകൾ &\nസബ്‌സ്',
    'smart_bin_status': 'സ്മാർട്ട് ബിൻ നില', 'view_all': 'എല്ലാം കാണുക →',
    'upcoming_pickup': 'വരാനിരിക്കുന്ന പിക്കപ്പ്',
    'scheduled_pickup': 'ഷെഡ്യൂൾ ചെയ്ത പിക്കപ്പ്',
    'confirmed': 'സ്ഥിരീകരിച്ചു', 'details': 'വിശദാംശങ്ങൾ', 'track': 'ട്രാക്ക്',
    'eco_impact': 'നിങ്ങളുടെ ഇക്കോ സ്വാധീനം 🌿',
    'schedule_pickup_title': 'പിക്കപ്പ് ഷെഡ്യൂൾ',
    'pickup_location': 'പിക്കപ്പ് സ്ഥലം',
    'select_date': 'തീയതി തിരഞ്ഞെടുക്കുക', 'select_time': 'സമയം തിരഞ്ഞെടുക്കുക',
    'confirm_schedule': 'ഷെഡ്യൂൾ സ്ഥിരീകരിക്കുക',
    'date': 'തീയതി', 'time': 'സമയം', 'location': 'സ്ഥലം',
    'marketplace': 'മാർക്കറ്റ്‌പ്ലേസ്', 'sell_waste': 'മാലിന്യം വിൽക്കുക',
    'payment': 'പേയ്‌മെന്റ്', 'pay_now': 'ഇപ്പോൾ പണം നൽകുക',
    'subscription': 'സബ്സ്ക്രിപ്ഷൻ',
    'settings': 'ക്രമീകരണങ്ങൾ', 'language': 'ഭാഷ', 'logout': 'ലോഗ്ഔട്ട്',
    'cancel': 'റദ്ദാക്കുക', 'total': 'ആകെ',
    'pickup_details': 'പിക്കപ്പ് വിശദാംശങ്ങൾ',
    'track_pickup': 'പിക്കപ്പ് ട്രാക്ക്',
    'continue_text': 'തുടരുക',
    'location_label': 'നിങ്ങളുടെ സ്ഥലം',
  };

  static const _ta = {
    'onboarding_title_1': 'Emptyko-க்கு வரவேற்கிறோம்',
    'onboarding_desc_1': 'உங்கள் விரல் நுனியில் ஸ்மார்ட் கழிவு மேலாண்மை.',
    'onboarding_title_2': 'ஸ்மார்ட் பின் கண்காணிப்பு',
    'onboarding_desc_2': 'நிகழ்நேர IoT சென்சார்கள் உங்கள் பின் நிலைகளை கண்காணிக்கின்றன.',
    'onboarding_title_3': 'விற்கவும் & மறுசுழற்சி செய்யவும்',
    'onboarding_desc_3': 'உங்கள் மறுசுழற்சி கழிவுகளை பணமாக மாற்றுங்கள்!',
    'choose_language': 'உங்கள் மொழியைத் தேர்வு செய்யுங்கள்',
    'choose_language_desc': 'தொடங்க மொழியைத் தேர்ந்தெடுக்கவும்',
    'get_started': 'தொடங்கு', 'next': 'அடுத்து', 'skip': 'தவிர்', 'back': 'பின்',
    'welcome_back': 'மீண்டும் வரவேற்கிறோம்!',
    'enter_phone': 'தொலைபேசி எண்ணை உள்ளிடவும்',
    'home': 'முகப்பு', 'pickup': 'பிக்கப்', 'smart_bin': 'ஸ்மார்ட் பின்',
    'history': 'வரலாறு', 'market': 'சந்தை',
    'login': 'உள்நுழை', 'sign_up': 'பதிவு செய்',
    'send_otp': 'OTP அனுப்பு',
    'continue_google': 'Google மூலம் தொடரவும்',
    'or_continue_phone': 'அல்லது தொலைபேசி மூலம் தொடரவும்',
    'quick_actions': 'விரைவு செயல்கள்',
    'schedule_pickup': 'பிக்கப்\nதிட்டமிடு',
    'smart_bin_action': 'ஸ்மார்ட்\nபின்', 'sell_recyclables': 'மறுசுழற்சி\nவிற்கவும்',
    'plans_subs': 'திட்டங்கள் &\nசந்தா',
    'settings': 'அமைப்புகள்', 'language': 'மொழி', 'logout': 'வெளியேறு',
    'cancel': 'ரத்து', 'total': 'மொத்தம்',
    'create_account': 'கணக்கை உருவாக்கு',
    'payment': 'பணம்', 'subscription': 'சந்தா',
    'continue_text': 'தொடரவும்',
  };

  static const _kn = {
    'onboarding_title_1': 'Emptyko ಗೆ ಸುಸ್ವಾಗತ',
    'onboarding_desc_1': 'ನಿಮ್ಮ ಬೆರಳ ತುದಿಯಲ್ಲಿ ಸ್ಮಾರ್ಟ್ ತ್ಯಾಜ್ಯ ನಿರ್ವಹಣೆ.',
    'onboarding_title_2': 'ಸ್ಮಾರ್ಟ್ ಬಿನ್ ಮಾನಿಟರಿಂಗ್',
    'onboarding_desc_2': 'ರಿಯಲ್-ಟೈಮ್ IoT ಸೆನ್ಸರ್‌ಗಳು ನಿಮ್ಮ ಬಿನ್ ಮಟ್ಟವನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡುತ್ತವೆ.',
    'onboarding_title_3': 'ಮಾರಾಟ ಮಾಡಿ & ಮರುಬಳಕೆ ಮಾಡಿ',
    'onboarding_desc_3': 'ನಿಮ್ಮ ಮರುಬಳಕೆ ತ್ಯಾಜ್ಯವನ್ನು ಹಣವಾಗಿ ಪರಿವರ್ತಿಸಿ!',
    'choose_language': 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'choose_language_desc': 'ಪ್ರಾರಂಭಿಸಲು ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'get_started': 'ಪ್ರಾರಂಭಿಸಿ', 'next': 'ಮುಂದೆ', 'skip': 'ಬಿಟ್ಟುಬಿಡಿ', 'back': 'ಹಿಂದೆ',
    'welcome_back': 'ಮರಳಿ ಸ್ವಾಗತ!',
    'enter_phone': 'ಫೋನ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ',
    'home': 'ಹೋಮ್', 'pickup': 'ಪಿಕ್‌ಅಪ್', 'smart_bin': 'ಸ್ಮಾರ್ಟ್ ಬಿನ್',
    'history': 'ಇತಿಹಾಸ', 'market': 'ಮಾರುಕಟ್ಟೆ',
    'login': 'ಲಾಗಿನ್', 'sign_up': 'ಸೈನ್ ಅಪ್',
    'send_otp': 'OTP ಕಳುಹಿಸಿ',
    'continue_google': 'Google ನೊಂದಿಗೆ ಮುಂದುವರಿಸಿ',
    'or_continue_phone': 'ಅಥವಾ ಫೋನ್ ನೊಂದಿಗೆ ಮುಂದುವರಿಸಿ',
    'quick_actions': 'ತ್ವರಿತ ಕ್ರಿಯೆಗಳು',
    'schedule_pickup': 'ಪಿಕ್‌ಅಪ್\nಶೆಡ್ಯೂಲ್',
    'smart_bin_action': 'ಸ್ಮಾರ್ಟ್\nಬಿನ್', 'sell_recyclables': 'ಮರುಬಳಕೆ\nಮಾರಾಟ',
    'plans_subs': 'ಯೋಜನೆಗಳು &\nಚಂದಾ',
    'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು', 'language': 'ಭಾಷೆ', 'logout': 'ಲಾಗ್ ಔಟ್',
    'cancel': 'ರದ್ದು', 'total': 'ಒಟ್ಟು',
    'create_account': 'ಖಾತೆ ರಚಿಸಿ',
    'payment': 'ಪಾವತಿ', 'subscription': 'ಚಂದಾ',
    'continue_text': 'ಮುಂದುವರಿಸಿ',
  };

  static const _te = {
    'onboarding_title_1': 'Emptyko కు స్వాగతం',
  };

  static const _mr = {
    'onboarding_title_1': 'Emptyko मध्ये आपले स्वागत आहे',
  };

  static const _bn = {
    'onboarding_title_1': 'Emptyko এ স্বাগতম',
  };

  static const _gu = {
    'onboarding_title_1': 'Emptyko માં તમારું સ્વાગત છે',
  };
}
