// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_PerFfPuZM0LXVHnaVwpxA5lbWAMPNcQ',
    appId: '1:588767696668:web:6da29ba2284e2f49970cd9',
    messagingSenderId: '588767696668',
    projectId: 'emptikko',
    authDomain: 'emptikko.firebaseapp.com',
    databaseURL: 'https://emptikko-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emptikko.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSO3cATW_otjpZXLuztgd1gmZ48IDGlsg',
    appId: '1:588767696668:android:dbbafa92473d5189970cd9',
    messagingSenderId: '588767696668',
    projectId: 'emptikko',
    databaseURL: 'https://emptikko-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emptikko.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrNksaRxeiDd-UGf8Sm8d0fxgiLzIcIrY',
    appId: '1:588767696668:ios:a5cf8a067fe66670970cd9',
    messagingSenderId: '588767696668',
    projectId: 'emptikko',
    databaseURL: 'https://emptikko-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emptikko.firebasestorage.app',
    iosClientId: '588767696668-g8fc2c714400urq63461kur4ul080dfj.apps.googleusercontent.com',
    iosBundleId: 'com.ecowaste.ecoWasteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrNksaRxeiDd-UGf8Sm8d0fxgiLzIcIrY',
    appId: '1:588767696668:ios:a5cf8a067fe66670970cd9',
    messagingSenderId: '588767696668',
    projectId: 'emptikko',
    databaseURL: 'https://emptikko-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emptikko.firebasestorage.app',
    iosClientId: '588767696668-g8fc2c714400urq63461kur4ul080dfj.apps.googleusercontent.com',
    iosBundleId: 'com.ecowaste.ecoWasteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsNf7uMBXGb_9pZmvO5PTf5NHAGdzNq9o',
    appId: '1:588767696668:web:058e5c7248fdfc2c970cd9',
    messagingSenderId: '588767696668',
    projectId: 'emptikko',
    authDomain: 'emptikko.firebaseapp.com',
    databaseURL: 'https://emptikko-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'emptikko.firebasestorage.app',
  );
}
